name: Deploy
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u ${{ env.DOCKER_USER }} -p ${{ env.DOCKER_PASSWORD }}

      - name: Create Docker image
        run: docker build -t allasydoriak/my-test-app .

      - name: Push image to Docker Hub
        run: docker push allasydoriak/my-test-app
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
    
    steps:
      - name: Connect to server and run new docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USERNAME }}
          password: ${{ env.SERVER_PASSWORD }}
          script: |
            docker login -u ${{ env.DOCKER_USER }} -p ${{ env.DOCKER_PASSWORD }}
            docker stop alla
            docker rmi allasydoriak/my-test-app:latest
            docker pull allasydoriak/my-test-app:latest
            docker run -d -p 8003:8003 --rm --name alla allasydoriak/my-test-app:latest

