name: Run-Tests

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Print node version
        run: node --version

      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'

      - run: npm install
      
      - run: npm run test
